#Makefile for Patata engine.
all: main.o App.o
	g++ -o patata main.o App.o 
	-LD:\Documents\Personal Projects\C++_Projects\Patata\dependencies\glad-master\Debug
	-ID:\Documents\Personal Projects\C++_Projects\Patata\dependencies\glad-master\include\glad